stages:
  - build
  - deploy
  - release

include:
  - services/backend/.gitlab-ci.yml
  - services/frontend/.gitlab-ci.yml

deploy testnet staging:
  stage: deploy
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose -f deploy/compose.testnet-staging.yml pull
    - docker-compose -f deploy/compose.testnet-staging.yml -p keepscan-staging-testnet up --remove-orphans -d
  only:
    refs:
      - master
  environment:
    name: testnet staging
    url: https://testnet.staging.keepscan.com

clean testnet staging:
  stage: deploy
  script:
    - docker-compose -f deploy/compose.testnet-staging.yml -p keepscan-staging-testnet down --rm
  when: manual
  only:
    refs:
      - master

deploy mainnet staging:
  stage: deploy
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose -f deploy/compose.mainnet-staging.yml pull
    - docker-compose -f deploy/compose.mainnet-staging.yml -p keepscan-staging-mainnet up --remove-orphans -d
  only:
    refs:
      - master
  environment:
    name: mainnet staging
    url: https://mainnet.staging.keepscan.com

clean mainnet staging:
  stage: deploy
  script:
    - docker-compose -f deploy/compose.mainnet-staging.yml -p keepscan-staging-mainnet down --rm
  when: manual
  only:
    refs:
      - master

release testnet:
  stage: release
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose -f deploy/compose.testnet.yml pull
    - docker-compose -f deploy/compose.testnet.yml -p keepscan-testnet up --remove-orphans -d
  only:
    refs:
      - master
  when: manual
  environment:
    name: testnet
    url: https://testnet.keepscan.com

release mainnet:
  stage: release
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose -f deploy/compose.mainnet.yml pull
    - docker-compose -f deploy/compose.mainnet.yml -p keepscan up --remove-orphans -d
  only:
    refs:
      - master
  when: manual
  environment:
    name: mainnet
    url: https://keepscan.com