stages:
  - build
  - deploy

include:
  - services/backend/.gitlab-ci.yml
  - services/frontend/.gitlab-ci.yml


deploy:production:
  stage: deploy
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose -f deploy/compose.yml pull
    - docker-compose -f deploy/compose.yml -p keepscan up --remove-orphans -d
  only:
    refs:
      - master