version: "3.8"
services:
  db:
    image: postgres:12
    restart: always
    volumes:
      - app-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=keepscan
      - POSTGRES_USER=keepscan
      - POSTGRES_PASSWORD=L9cZA9npgWEr94QpqgwyaQ73
  bi:
    image: metabase/metabase
    ports:
      - 50025:3000
    restart: always
    depends_on:
      - bi-db
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_USER=keepscan-bi
      - MB_DB_PASS=L9cZA9npgWEr94QpqgwyaQ73
      - MB_DB_PORT=5432
      - MB_DB_HOST=bi-db
      - MB_DB_DBNAME=keepscan-bi
  bi-db:
    image: postgres:12
    restart: always
    volumes:
      - bi-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=keepscan-bi
      - POSTGRES_USER=keepscan-bi
      - POSTGRES_PASSWORD=L9cZA9npgWEr94QpqgwyaQ73
  db-admin:
    image: dpage/pgadmin4
    ports:
      - 50029:80
    restart: always
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@keepscan.com
      - PGADMIN_DEFAULT_PASSWORD=$ADMIN_PASSWORD
  api:
    image: registry.gitlab.com/emerido/keepscan/backend:latest
    ports:
      - 50020:80
    restart: always
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  web:
    image: registry.gitlab.com/emerido/keepscan/frontend:latest
    ports:
      - 50022:80
    restart: always
volumes:
  bi-data:
  app-data: